<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Add a New Student</h3>
            </div>
            <div class="panel-body">
                <p>Ceate a new dorm student.</p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('addStudent');?>">Add Student</a></p>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Students</h3>
            </div>
            <div class="panel-body">
                <table class="table table-striped table-bordered">
                    <thead>
                        <tr>
                            <th>Student Name</th>
                            <th>Student Number</th>
                            <th>Gender</th>
                            <th>Date of Birth</th>
                            <th>Address</th>
                            <th>Phone Number</th>
                            <th>View</th>
                            <th>Edit</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php foreach ($students as $student) { ?>
                        <tr>
                            <td><?php echo $student['full_name']; ?></td>
                            <td><?php echo $student['student_num']; ?></td>
                            <td><?php echo $student['gender']; ?></td>
                            <td><?php echo $student['birth_date']; ?></td>
                            <td><?php
                                echo $student['address_1'];
                                if ($student['address_2'] != '') {
                                    echo ' ' . $student['address_2'];
                                }

                                echo ', '
                                    . $student['city'] . ', '
                                    . $student['state'] . ' '
                                    . $student['zip'];
                            ?></td>
                            <td><?php echo $student['phone_number']; ?></td>
                            <td><a class="btn btn-primary" href="<?php echo $this->url('viewStudent', array('studentId' => $student['id']));?>">View</a></td>
                            <td><a class="btn btn-primary" href="<?php echo $this->url('editStudent', array('studentId' => $student['id']));?>">Edit</a></td>
                            <td><a class="btn btn-primary" href="<?php echo $this->url('deleteStudent', array('studentId' => $student['id']));?>">Delete</a></td>
                        </tr>
                        <?php } ?>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
