<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Add a New Student</h3>
            </div>
            <div class="panel-body">
                <p>Ceate a new dorm student.</p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('addStudent');?>">Add Student</a></p>
            </div>
        </div>
    </div>
</div>
