<?php if (isset($this->messages)) {?>
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4>Warning!</h4>
        <ul>
        <?php
        foreach ($this->messages as $element => $errors) {
            foreach ($errors as $messageID => $message) {
                $item = $this->form->get($element)->getLabel();
                echo "<li>$item: $message</li>\n";
            }
        }
        ?>
        </ul>
    </div>
<?php } elseif (isset($this->success)) {?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php echo $this->success; ?>
    </div>
<?php }


$form->setAttributes(array(
    'class' => 'form-horizontal'
));
$form->prepare();

echo $this->form()->openTag($form);
echo "\n";

foreach ($form as $element) {?>
    <div class="form-group">
        <?php 
            $type = $element->getAttribute('type');
            $name = $element->getAttribute('name'); 
            $label = $element->getLabel();
        ?>
        <?php if ($type == 'hidden') { ?>
            <div class="hidden"><?php echo $this->formElement($element); ?></div>
        <?php } else if ($type == 'submit') { ?>
            <?php
                if ($element->getValue()) {
                    $value = $element->getValue();
                } elseif ($element->getAttribute('value')) {
                    $value = $element->getAttribute('value');
                } elseif ($element->getAttribute('caption')) {
                    $value = $element->getAttribute('caption');
                } else {
                    $value = 'Submit';
                }
                $id = $element->getAttribute('id'); 
            ?>
                <div class="col-xs-offset-3 col-xs-10">
                    <input type="submit" class="btn btn-primary submit-btn" value="<?php echo $value; ?>" id="<?php echo $id; ?>" name="<?php echo $name; ?>">
                </div>
        <?php } else if ($type == 'select') { ?>
                <label class="control-label col-xs-3"><?php echo $label ?></label>
                <div class="col-xs-9">
                    <select class="form-control" name="<?php echo $name ?>" <?php
                        $validators = $form->getInputFilter()->get($name)->getValidatorChain()->getValidators();
                        if (count($validators) > 0) {
                            echo 'validate="';
                            foreach ($validators as $validator) {
                                $validator_name = get_class($validator['instance']);
                                $validator_name = preg_replace('@.*\\\\@', '', $validator_name);
                                echo "$validator_name ";
                            }
                            echo '"';
                        }

                        if ($element->getOption('required')) {
                            echo ' required="required"';
                        }

                    ?> >
                    <?php foreach ($element->getValueOptions() as $key => $value) { ?>
                        <option value="<?php echo $key; ?>"><?php echo "$value"; ?></option>
                    <?php } ?>
                    </select>
                </div>
        <?php } else if ($label != '') { ?>

                <label class="control-label col-xs-3"><?php echo $label ?></label>
                <div class="col-xs-9">
                    <input class="form-control" name="<?php echo $name ?>" type="<?php echo $type ?>" <?php
                        $validators = $form->getInputFilter()->get($name)->getValidatorChain()->getValidators();
                        if (count($validators) > 0) {
                            echo 'validate="';
                            foreach ($validators as $validator) {
                                $validator_name = get_class($validator['instance']);
                                $validator_name = preg_replace('@.*\\\\@', '', $validator_name);
                                echo "$validator_name ";
                            }
                            echo '"';
                        }

                        if ($element->getOption('required')) {
                            echo ' required="required"';
                        }

                    ?> />
                </div>
        <?php } ?> 
    </div>
<?php 
}
echo $this->form()->closeTag();
