
<?php if (isset($this->messages)) {?>
    <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <h4>Warning!</h4>
        <ul>
        <?php
        foreach ($this->messages as $element => $errors) {
            foreach ($errors as $messageID => $message) {
                $item = $this->form->get($element)->getLabel();
                echo "<li>$item: $message</li>\n";
            }
        }
        ?>
        </ul>
    </div>
<?php } elseif (isset($this->success)) {?>
    <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <?php echo $this->success; ?>
    </div>
<?php } ?>

<?php echo $this->bootstrapForm($form, array(
    'indent' => 4,
)); ?>
