<div class="jumbotron">
    <h1>Welcome to <strong>Dorm Assigner</strong></h1>

    <p>This application is designed to help dorm coordinators manage your busy dorms. You will be able to maintain a list of students which can then be added to individual dorm rooms. Each dorm unit will be able to house either male or female students, and will be divided into the various floors and dormitories.</p>
</div>
