<div class="jumbotron">
    <h1>Welcome to <strong>Dorm Assigner</strong></h1>

    <p>This application is designed to help dorm coordinators manage your busy dorms. You will be able to maintain a list of students which can then be added to individual dorm rooms. Each dorm unit will be able to house either male or female students, and will be divided into the various floors and dormitories.</p>
</div>

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Create a New Student</h3>
            </div>
            <div class="panel-body">
                <p>Add a new dorm student.</p>
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('addStudent');?>">Add Student</a></p>
            </div>
        </div>
    </div>
</div>
