<ul class="nav navbar-nav">
	<?php foreach ($this->container as $page): ?>
        <?php /* @var $page Zend\Navigation\Page\Mvc */ ?>

        <?php if( ! $page->isVisible() || !$this->navigation()->accept($page)) continue; ?>

        <?php if( ! $page->hasPages()): ?>
        <li <?php if($page->isActive()) echo 'class="active"'?>>
            <a class="nav-header" href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a>
        </li>

        <?php else: ?>
        <li class="dropdown<?php if($page->isActive()) echo ' active'?>">
            <a class="nav-header" href="<?php echo $page->getHref() ?>"><?php echo $this->translate($page->getLabel()) ?></a>

            <ul class="dropdown-menu">
            <?php foreach($page->getPages() as $child): ?>

                <?php if( ! $child->isVisible() || !$this->navigation()->accept($child)) continue; ?>

                <li <?php if($child->isActive()) echo 'class="active"'?>>
                    <a href="<?php echo $child->getHref() ?>"><?php echo $this->translate($child->getLabel()) ?></a>
                </li>
            <?php endforeach ?>
            </ul>
		 </li>   

		<?php endif ?>
    <?php endforeach ?>
</ul>
