<div class="row">
    <div class="col-md-4">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Dorm <?php echo $this->dorm->getName() ; ?></h3>
            </div>
            <div class="panel-body">
                <p><a class="btn btn-primary pull-right" href="<?php echo $this->url('addStudent');?>">View Dorm <?php echo $this->dorm->getId(); ?></a></p>
            </div>
        </div>
    </div>
</div>
